steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/hyscale-dev-env/hyscale/build/test:test', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/hyscale-dev-env/hyscale/build/test:test']

- name: 'gcr.io/cloud-builders/gcloud'
  id: Clone env repository
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    git clone https://github.com/srujankujmar/deploy.git
    cd deploy && \
    git config --global user.name "srujankujmar"
    git config user.email "srujankumar.gourishetty@gmail.com"
    touch test
    git add .
    git commit -m "test push"
    git push origin main

